server:
  port: 8890
eureka:
  instance:
    hostname: localhost
#    appname: eureka-server1 # 服务名 配置优先级高于 spring.application.name
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/
spring:
  application:
    name: eureka-server